CREATE TABLE user_admin (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_influencer (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    foto_profile VARCHAR(255) DEFAULT NULL,
    link_ig VARCHAR(255) DEFAULT NULL,
    link_fb VARCHAR(255) DEFAULT NULL,
    link_tiktok VARCHAR(255) DEFAULT NULL,
    link_youtube VARCHAR(255) DEFAULT NULL,
    konten VARCHAR(255) DEFAULT NULL,
    pengenalan TEXT DEFAULT NULL,
    nomor_hp VARCHAR(15) DEFAULT NULL,
    tanggal_lahir DATE DEFAULT NULL,
    kota VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE USER_BISNIS (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nama_bisnis VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    foto_profile VARCHAR(255) DEFAULT NULL,
    website VARCHAR(255) DEFAULT NULL,
    nomor_telepon VARCHAR(20) DEFAULT NULL,
    deskripsi TEXT DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE kolaborasi (
    id INT(11) NOT NULL AUTO_INCREMENT,
    id_influencer INT(11) NOT NULL,
    id_bisnis INT(11) NOT NULL,
    detail_kolaborasi TEXT DEFAULT NULL,
    id_campaign INT(11) DEFAULT NULL,
    status ENUM('pending', 'diterima', 'ditolak', 'selesai') DEFAULT 'pending',
    tanggal_pengajuan TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tanggal_disetujui TIMESTAMP NULL,
    alasan_penolakan TEXT DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_influencer) REFERENCES USER_INFLUENCER (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_bisnis) REFERENCES USER_BISNIS (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE campaign (
    id INT(11) NOT NULL AUTO_INCREMENT,
    id_bisnis INT(11) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    target_dana DECIMAL(15,2) NOT NULL,
    dana_terkumpul DECIMAL(15,2) DEFAULT 0.00,
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status ENUM('draft', 'aktif', 'selesai', 'batal') DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (id_bisnis) REFERENCES USER_BISNIS(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
